redmine:
  restart: always
#  build: redmine
  #image: alpine-redmine
  image: inspiredgeek/redmine-alpine
  environment:
    - TZ=Asia/Seoul
#   - LANG=C.UTF-8
  ports:
    - "3000:3000"
  volumes:
    - /data/scm/files:/usr/src/redmine/files
    - /data/scm/db:/usr/src/redmine/sqlite
    - /data/scm/log:/usr/src/redmine/log
#    - /data/scm/plugins:/usr/src/redmine/plugins

jenkins:
  restart: always
  image: jenkins:alpine
  environment:
    - TZ=Asia/Seoul
    - JENKINS_OPTS=--prefix=/jenkins
  ports:
    - 8080:8080
    - "50000:50000"
  volumes:
    - /data/jenkins/:/var/jenkins_home
    - ~/.m2/repository/:/var/jenkins_home/.m2/repository

svn:
  image: pikado/alpine-svn
  #build: alpine-svn
  #container_name: alpine_svn
  #hostname: alpine-svn
  environment:
  - DAV_SVN_USER=hodorii
  - DAV_SVN_PASS=thdghtjd0
  - SVN_REPO=ecodi
  volumes:
  - /data/scm/svnrepo:/var/svn
  restart: always

artifactory:
   restart: always
   build: artifactory
   environment:
     - TZ=Asia/Seoul
     - JAVA_OPTS=-Xms256M -Xmx256M
   volumes:
     - /data/artifactory/data:/usr/local/artifactory/data
     - /data/artifactory/etc:/usr/local/artifactory/etc
     - /data/artifactory/logs:/usr/local/artifactory/logs
     - /data/artifactory/backup:/usr/local/artifactory/backup

#git:
# image: gitlab/gitlab-ce
# ports:
#  - "80:80"
#  - "2222:22"
#  - "443:443"
# volumes:
#   - ./scm/git:/etc/gitlab
#   - /var/opt/gitlab
#   - /var/log/gitlab

# cloud:
#   image: tomcat:7
#   ports:
#    - "80:8080"

# devtest:
#   image: tomcat:7
#   ports:
#    - "80:8080"


# db:
#  image: mysql:5.7
#  environment:
#   - MYSQL_ROOT_PASSWORD=admin
#   - MYSQL_DATABASE=sonar
#   - MYSQL_USER=sonar
#   - MYSQL_PASSWORD=sonar
#  ports:
#   - "3306:3306"
#  volumes:
#   - /data/mysql:/var/lib/mysql

# sonarqube:
#  image: sonarqube
#  links:
#   - db
#  environment:
#   - SONARQUBE_JDBC_USERNAME=sonar
#   - SONARQUBE_JDBC_PASSWORD=sonar
#   - SONARQUBE_JDBC_URL=jdbc:mysql://localhost/sonar;useUnicode=true
#  ports:
#   - "9000:9000"
#   - "9092:9092"

nginx:
   restart: always
   image: "nginx:alpine"
   volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
   ports:
   - "80:80"
   environment:
   - TZ=Asia/Seoul
   links:
   - redmine:redmine
   - jenkins:jenkins
#   - svn:svn
#   - artifactory:artifactory
